# Generated by Django 4.2.5 on 2023-10-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('techid', models.IntegerField()),
                ('techname', models.CharField(max_length=10)),
                ('techmail', models.CharField(max_length=20)),
                ('techpass', models.CharField(max_length=22)),
            ],
        ),
    ]
