# Generated by Django 4.2.5 on 2023-11-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Roll', models.IntegerField(unique=True)),
                ('city', models.CharField(max_length=70)),
                ('Marks', models.IntegerField()),
                ('Pass_date', models.DateField()),
            ],
        ),
    ]
