# Generated by Django 4.2.5 on 2023-10-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='Description',
            field=models.TextField(max_length=100),
        ),
    ]
