# Generated by Django 4.2.5 on 2023-10-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuid', models.IntegerField()),
                ('stname', models.CharField(max_length=50)),
                ('stemail', models.EmailField(max_length=60)),
            ],
        ),
    ]
