# Generated by Django 4.2.5 on 2023-10-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('userpassword', models.CharField(max_length=50)),
            ],
        ),
    ]
