# Generated by Django 4.2.5 on 2023-10-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hostel',
            fields=[
                ('hostel_room', models.IntegerField(primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=50)),
                ('stu_age', models.IntegerField()),
            ],
        ),
    ]
