# Generated by Django 4.2.5 on 2023-10-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('stuid', models.IntegerField(primary_key=True, serialize=False)),
                ('stuname', models.CharField(max_length=50)),
                ('stuemail', models.EmailField(max_length=100)),
                ('stupassword', models.CharField(max_length=50)),
            ],
        ),
    ]
