# Generated by Django 4.2.5 on 2023-10-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stuname',
            field=models.CharField(db_column='Name', max_length=50),
        ),
    ]
