# Generated by Django 4.2.5 on 2023-10-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_stuname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stuemail',
            field=models.EmailField(db_column='Email', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='stupassword',
            field=models.CharField(db_column='Password', max_length=50),
        ),
    ]
